# Generated by Django 4.1.5 on 2023-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="passing_career",
            field=models.TextField(null=True),
        ),
    ]
