# Generated by Django 4.1.5 on 2023-07-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0004_player_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="count", field=models.IntegerField(default=0),
        ),
    ]
